#
# File      : SConscript
# This file is part of RT-Thread RTOS/WebNet Server
# COPYRIGHT (C) 2011, Shanghai Real-Thread Technology Co., Ltd
#
# All rights reserved.
#
# Change Logs:
# Date           Author       Notes
# 2011-08-02     Bernard      the first version
#

Import('RTT_ROOT')
from building import *

src	= Split("""
mimetype.c
module.c
request.c
session.c
util.c
webnet.c
module/module_asp.c
module/module_auth.c
module/module_cgi.c
module/module_index.c
module/module_alias.c
module/module_log.c
""")

CPPPATH = [GetCurrentDir()]
group = DefineGroup('webnet', src, depend = ['RT_USING_LWIP'], CPPPATH = CPPPATH)

Return('group')
